### ISSUE TITLE
Cannot create window if component is not in entryComponents

### ISSUE THREAD

**Issue by unlight** [yujuiting/ng2-window-view#2]
To open window by `WindowService.pushWindow` component must have ComponentFactory.
So it must be pre-compiled (thats why all window components are defined in `entryComponents` section)

Putting components `entryComponents` section slows down start application, because `entryComponents` must be precompiled before can app start.

Can you eliminate this restriction?

**Comment by yujuiting** [comment]
Yes, its's possible totally dynamic loading component, but it may be a chaos in large project with lots of ngModule I guess.

First, wrapping anything you want to lazy loaded to a module.
```typescript
@NgModule({
  import: [WindowViewModule],
  entryComponent: [SimpleWindowComponent]
})
export class SimpleWindowModule {}
```

2. Load module before using
```typescript
import { Compiler } from '@angular/core';
import { SimpleWindowModule } from '../some/where';
import { WindowViewService } from 'ng2-window-view';

class AppComponent {
  constructor(private compiler: Compiler, private windowView: WindowViewService) {}

  openWindow() {
    this.compiler.compileModuleAndAllComponentsAsync(SimpleWindowModule).then( module => {
      let componentFactory = module.componentFactories.find(/* find your component */);
      // I fix something in this method for accept factory directly.
      windowView.pushWindow(componentFactory);
    });
  }
}
```

**Comment by unlight** [comment]
Yes, and without many `ngModule`s too.
Similar to [this](https://github.com/500tech/angular2-tree-component/blob/6749293074faf419ede079bb05d096a2d009c317/lib/components/adhoc-component-factory.service.ts#L19-L30).

**Comment by yujuiting** [comment]
Hey!
Please checkout v0.1.1 and [this document](https://github.com/yujuiting/ng2-window-view/blob/master/docs/dynamic-compile.md).
Hope those is helpful to you.
